### ISSUE TITLE
The fork now worked here, however the audio still sounds mono for some reason

### ISSUE THREAD

**Issue by jefecker** [cehbab/mono-to-stereo#1]
Well, I'm commenting here cuz the topic there was closed by the admin.

Basically, I was brought to that topic because of [this one](https://obsproject.com/forum/threads/usb-capture-device-mono-instead-of-multi-channel.138243/). The issue that most of them have is basically the same as mine in one specific question: me and them have a non-branded capture device bought from China. (my one is for RCA/AV capturing)
In my case I don't know what happened, don't know even if this issue is limited to generic capture devices and if it even has an actual solution. But now a small apparent issue is shown in log after "Press Enter to quit..." even if the progress works successfully, while the audio stays sounding mono.

```
mono-to-stereo.exe --in-device "Microphone (2- USB2.0 MIC)" --out-device "Speakers (Realtek High Definition Audio)"
<< Microphone (2- USB2.0 MIC)
>> Speakers (Realtek High Definition Audio)
 Channels 2 -> 2
 BitsPerSample 32 -> 32
 SamplesPerSec 24000 -> 48000
Press Enter to quit...

Probably spurious glitch reported after 960 frames
Probably spurious glitch reported after 1056 frames
```

This happens independently if I use my computer driver (Realtek) or VoiceMeeter. Is there a way to know if this is a hardware problem or not?

**Comment by cehbab** [comment]
That's from the original code.
Its even in the parent of that!.
https://github.com/mvaneerde/blog/blob/main/loopback-capture/loopback-capture/loopback-capture.cpp

The audio device is reporting AUDCLNT_BUFFERFLAGS_DATA_DISCONTINUITY when it accesses the buffer,
but then it uses that data anyways.
I get it sometimes, and others I do not...
Its logging this information but ignoring it and using the audio buffer data it fetched anyways.
So its just logging as far as I can tell and not an issue.

I use mine mainly with an el-cheapo usb hdmi capture dongle to use an xbox on my pc monitor :)
